apiVersion: apps/v1
kind: Deployment
metadata:
  name: firefox
spec:
  selector:
    matchLabels:
      app: firefox
  template:
    metadata:
      labels:
        app: firefox
    spec:
      containers:
      - name: firefox1
        image: jlesage/firefox
        ports:
        - containerPort: 3001
